### ISSUE TITLE
Example files don't rebuild?

### ISSUE THREAD

**Issue by donnielrt** [janhuenermann/neurojs#9]
Hey, awesome project!

I might be missing something, but I'm not able to change any of the source files in `src` or `example/cars`, the files aren't rebuilt, even after running `npm run build`. Is there a step/configuration I'm missing?

**Comment by janhuenermann** [comment]
Hey, 

just execute `webpack`. That should rebuild the dist file. `npm run build` doesn't work because it's wrongly configured right now.

**Comment by donnielrt** [comment]
Thanks, that worked! I'm trying to modify the example to start with a base env/brain since otherwise it has to start from scratch every time I reload the page, but it looks like the `car-demo.bin` you've got [here](http://janhuenermann.com/projects/learning-to-drive) isn't compatible with the "open brain file" or "open world file" in the examples? 

Would you happen to have compatible saved files available?

**Comment by janhuenermann** [comment]
Yes that's true, it isn't compatible because it contains the world as well as the brain in one file. Maybe I'll port that functionality over at sometime. Unfortunately I only have the combined file.

But actually there is a checkpoint in the repo, try to open the `examples/cars/checkpoint/agent/121216-12h-training.bin` file with "Open brain file". Or you can train your own and when it's done training, save the brain file with "Save agent".

**Comment by donnielrt** [comment]
Oh, excellent, thank you!
